eventlist/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("events/", include("events.urls")),
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),

]

handler404 = "eventlist.views.handler404"

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    # path("", views.index, name="polls_index"),
    path("", views.IndexView.as_view(), name="polls_index"),
    path("forms/", views.get_name, name="name_form"),
    path("users/authenticate/", views.authenticate_user, name="users_authenticate"),
    path("users/login", views.view_login, name="user_login"),
    path("users/logout", views.handle_logout, name="user_logout"),
    path("users/create-account", views.register_user, name="poll_create_user"),
    path("users/register", views.add_user, name="poll_users"),
    path("<int:question_id>/", views.detail, name="detail"),
    # path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="result"),
    # path("<int:question_id>/results/", views.result, name="result"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("questions/", views.question_page, name="question")
]

polls/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date_published")

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)
    choice_text = models.CharField(max_length=200)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms


class NameForm(forms.Form):
    your_name = forms.CharField(label="Your name", max_length=100)

polls/views.py
from typing import Any
from django.db import models
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from .models import Question, Choice
from django.urls import reverse
from django.views import generic

# Working with users
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from .forms import NameForm


def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return redirect("polls:user_login")

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, "polls/name.html", {"form": form})
# Create your views here.

# The user pass test conducts a test on the logged in user before moving them
# to the route of choice


def email_check(user):
    return user.email.endswith("@example.com")


def index(request):
    template = loader.get_template("polls/index.html")
    context = {
        "colors": ["Blue", "Green", "Red"],
        "is_valid": True,
        "name": "Jonathan Messiah",
        "message": "We have been talking about the possibility of a military confrontation",
        "blog_entries": [
            {
                "title": "Hired by MFS Africa as a Backend Developer",
                "body": "I am hoping to get a job at MFS as a backend Developer"
            }
        ]
    }

    return render(request, "polls/child.html", context)


def question_page(request):
    latest_questions = Question.objects.order_by("pub_date")[:5]

    context = {
        "latest_questions": latest_questions
    }

    return render(request, "polls/question.html", context)


@login_required
@user_passes_test(email_check)
def detail(request, question_id):
    # if not request.user.is_authenticated:
    #     return redirect("polls:user_login")
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exists")
    # return HttpResponse('You are viewing question %s' % question)
    question = get_object_or_404(Question, pk=question_id)

    return render(request, "polls/detail.html", {"question": question})


def result(request, question_id):
    # response = "This is the result page for question %s"
    # return HttpResponse(response % question_id)
    question = get_object_or_404(Question, pk=question_id)

    return render(request, "polls/results.html", {"question": question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])

    except (KeyError, Choice.DoesNotExist):
        return render(request, "polls/details.html", {
            "question": question,
            "error_message": "You did not select a choice"
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse("polls:result", args=(question_id,)))


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        ''' Return the last five published questions '''
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):

    model = Question
    template_name = "polls/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def add_user(request):
    try:
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        firstName = request.POST["firstname"]

        User.objects.create_user(
            username=username,
            email=email,
            password=password,
            first_name=firstName
        )
        return HttpResponse("The user was created successfully", status_code=200)
    except KeyError as error:
        print(error)
        return HttpResponse(error)


def register_user(request):
    return render(request, "polls/register.html")


def update_password_handler(request):
    try:
        username = request.POST["username"]
        password = request.POST["password"]

        user = User.objects.get(username=username)
        if user is not None:
            user.set_password(password)
            user.save()
            return HttpResponse("Password updated")
        else:
            return HttpResponse("Password not updated")
    except KeyError as error:
        print(error)
        return HttpResponse(error)


def update_password(request):
    return render(request, "polls/password-update.html")


def authenticate_user(request):
    try:
        username = request.POST["username"]
        password = request.POST["password"]  # "12345678abcdABCD"
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user, backend=None)

            return HttpResponse("Login successful")
        else:
            return HttpResponse("Login is not successful")
    except KeyError as error:
        print(error)
        return HttpResponse("Please, fill the form correctly")


def view_login(request):
    return render(request, "polls/login.html")


def handle_logout(request):
    logout(request)
    return redirect("polls:user_login")

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="style.css">
    <title>{% block title %}My amazing site{% endblock %}</title>
</head>

<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/blog/">Blog</a></li>
        </ul>
        {% endblock %}
    </div>
    <div id="example">
        {% block example %}
            <h2> Na me add this example</h2>
        {% endblock %}
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>

</html>

polls/templates/polls/child.html
{% extends "polls/base.html" %}

{% block title %}My amazing blog{% endblock %}

{% block example %}
    <div>
        <h5>I come override am here</h5>
    </div>
{% endblock %}

{% block content %}
{% for entry in blog_entries %}
    <h2>{{ entry.title }}</h2>  
    <p>{{ entry.body }}</p>
{% endfor %}
{% endblock %}

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {%csrf_token%}
    <fieldset>
        <legend>
            <h1> {{question.question_text}} </h1>
        </legend>
        {% if error_message %}
            <p> <strong> {{ error_message }} </strong></p>
        {% endif %} 

        {% for choice in question.choice_set.all %} 
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="vote"/>
</form>

polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Working with Django Templating</title> 
    <meta charset="utf-8">
    <meta name="viewport" content="width=initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>
    <h1>Poll Index Page </h1>
    {% if is_valid %}
        <p> Show {{ name }} </p>
    {% else  %}
        <p> Variable no dey </p>
    {% endif %}
    
    {% for color in colors %}
    <li> {{color}} </li>
    {% endfor %}
    <h3>Enjoying Django Templating</h3>
    <div> {{ message|truncatewords:5 }}</div>
    <p> See my figure</p> 
    <!-- <img src="{% static 'downtime.png' %}" alt="Figure"> -->
</body>
</html>

polls/templates/polls/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Authentication: Login </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>

<body>
    
    <form method="post" action="{% url 'polls:users_authenticate'  %}" class="login-form">
        {%csrf_token%}
        <h1>Account Login</h1>
        <label for="username">Username</label>
        <input type="text" name="username">
        <label for="password">Password</label>
        <input type="password"  name="password">
        <button type="submit" id="submit">Login</button>
    </form>
</body>

</html>

polls/templates/polls/name.html
<form action="{% url 'polls:name_form' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

polls/templates/polls/password-update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Authentication: Register </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>

<body>
    <h1>Update your password</h1>

    <form method="post" action="{% url 'polls:poll_users'  %}">
        {%csrf_token%}
        <label for="username">Username</label>
        <input type="text" name="username">
        <label for="password">Password</label>
        <input type="password" name="password">
        <button type="submit">Update</button>
    </form>
</body>

</html>

polls/templates/polls/question.html
{% extends "polls/base.html" %} 
{% block title %} Questions Page {% endblock %} 

{% block sidebar %} <h2> My Sidebar </h2> {% endblock %} 

{% block content %} 
    {% if latest_questions|length > 0 %}
        {% for question in latest_questions %} 
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li> 
        {% endfor %} 
    {% else %} 
        <p>No Question Yet</p> 
    {% endif %} 
{% endblock %}

polls/templates/polls/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Authentication: Register </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <style>
        .login-form,
        form {
            margin: 0 auto;
            width: 40%;
            padding: 2rem
        }
    
        button,
        input,
        select,
        textarea {
            font-family: inherit;
            font-size: 1.5em;
        }
    
        input,
        textarea,
        button {
            box-sizing: border-box;
            width: 80%;
            padding: 8px;
            font-size: 1.1rem;
            outline: 0;
            display: block;
            margin-bottom: 1.5rem;
            border: 1px solid #eee;
            border-radius: 5px;
            -webkit-appearance: none;
            appearance: none;
    
        }
    
        label {
            margin-right: 10px;
            font-size: 1.2rem;
        }
    
        label:not(.class-name) {
            display: block;
            margin-bottom: 1rem;
            margin-right: 0;
        }
    
        #submit {
            background: rgb(23, 39, 8);
            color: #fff;
        }
    
        h1 {
            text-align: center;
        }
    </style>
</head>

<body>
    <h1>Signup as a member</h1>

    <form method="post" action="{% url 'polls:poll_users'  %}">
        {%csrf_token%}
        <label for="username">Username</label>
        <input type="text" name="username">
        <label for="email">Email</label>
        <input type="email" name="email">
        <label for="firstname">First Name</label>
        <input type="text" name="firstname">
        <label for="password">Password</label>
        <input type="password" name="password">
        <button type="submit" id="submit">Signup</button>
    </form>
</body>

</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>